### PR TITLE
renamed iam-client initDID to createDocument

### PR DESCRIPTION
**Pull request by hrachocode**

### CODE REVIEW

**Review by JGiter — CHANGES_REQUESTED** [review]
Since library API has changed we should reflect it in new major version. For this please change commit message like 
```
refactor: rename initDID to createDocument

BREAKING CHANGE: change initialization API
```

**Comment by hrachocode** [comment]
> Since library API has changed we should reflect it in new major version. For this please change commit message like
> 
> ```
> refactor: rename initDID to createDocument
> 
> BREAKING CHANGE: change initialization API
> ```

done https://github.com/energywebfoundation/iam-client-lib/pull/227/commits/b1929322487c6368d54457cbad5c59f9ffc35afa

**Comment by JGiter** [comment]
> > Since library API has changed we should reflect it in new major version. For this please change commit message like
> > ```
> > refactor: rename initDID to createDocument
> > 
> > BREAKING CHANGE: change initialization API
> > ```
> 
> done [b192932](https://github.com/energywebfoundation/iam-client-lib/commit/b1929322487c6368d54457cbad5c59f9ffc35afa)

Sorry for not pointing out before, but there is important that between `refactor` and `BREAKING CHANGE` is two new lines (https://gist.github.com/brianclements/841ea7bffdb01346392c#footer)

**Comment by hrachocode** [comment]
> > > Since library API has changed we should reflect it in new major version. For this please change commit message like
> > > ```
> > > refactor: rename initDID to createDocument
> > > 
> > > BREAKING CHANGE: change initialization API
> > > ```
> > 
> > 
> > done [b192932](https://github.com/energywebfoundation/iam-client-lib/commit/b1929322487c6368d54457cbad5c59f9ffc35afa)
> 
> Sorry for not pointing out before, but there is important that between `refactor` and `BREAKING CHANGE` is two new lines (https://gist.github.com/brianclements/841ea7bffdb01346392c#footer)

please check https://github.com/energywebfoundation/iam-client-lib/pull/227/commits/bc86ec15d17151065f9a6875f4b17eeb1ff6150e

not sure if this is the way it should be
image
here is how it looks like

**Review by ahmedolaibrahim — APPROVED** [review]
Looks good to me. @hrachocode for future purpose, it's always important to give a description about what your PRs do. I think there's a document on JIRA about this.

I think we should also have release notes that specify the type of changes and what users of the library should expect.

**Comment by JGiter** [comment]
Last three commits are identical and at least last two of them triggers new major version. Please reset to `b08a68a` and commit breaking change on it

**Comment by hrachocode** [comment]
> Last three commits are identical and at least last two of them triggers new major version. Please reset to `b08a68a` and commit breaking change on it

moved to `b08a68a` made couple of changes related to generating docs with new version of typedoc and typedoc-markup-plugin and pushed with breaking change commit, please check

https://github.com/energywebfoundation/iam-client-lib/pull/227/commits/585a4ee012b7e3b16d4839d8f903c9aeec760665

**Review by JGiter — APPROVED** [review]

**Pull request merged**
