### PR TITLE
refactor(cache): refactor cache client types

### PR DESCRIPTION
**Pull request by Harasz**

### CODE REVIEW

**Comment by Harasz** [comment]
I was investigating error 500 on ICS, when I saw in ICL that we are passing wrong params names and TSC wasn't complaining about it (src/cacheServerClient/cacheServerClient.ts line: 243 & 253). So after a discussion with @JGiter we decided to refactor params types in cache client implementation to avoid such error in the future.

**Review by jrhender — APPROVED** [review]
Looks good to me, just need to fix the build

**Review by JGiter — APPROVED** [review]
Looks good, though there are some overkill from my point of view. For example, parameters wrapping single property like `GetOwnerParam` neither reduces amount of code nor make it more readable

**Comment by JGiter** [comment]
Closed because of https://github.com/energywebfoundation/iam-client-lib/pull/279

**Pull request closed without merging**
