### PR TITLE
Fixing isBrowser logic and adding tests

### PR DESCRIPTION
**Pull request by jrhender**
I think the logic of `isBrowser` might have been backwards. I added some tests and fixed. Let me know if this makes sense

### CODE REVIEW

**Comment by jrhender** [comment]
@JGiter I am confused however how the `isRunningBrowser` checks worked if the `isBrowser` logic was indeed incorrect 🤔 
Does this make sense to you?

**Review by JGiter — COMMENTED** [review]
defining the environment by checking `process` variable is not reliable because this var can be overridden. Better to check the global variable in a function that will be executed in the global scope:

```
const isBrowser = new Function ("try {return this === window;} catch (e) {return false;}");
if (isBrowser ()) console.log ("running under browser");
```
Also there is a npm package `is-browser`

**Comment by JGiter** [comment]
> @JGiter I am confused however how the `isRunningBrowser` checks worked if the `isBrowser` logic was indeed incorrect 
> Does this make sense to you?

Probably webpack adds process object to the build
image

**Comment by jrhender** [comment]
@JGiter So as I understand it, the `isBrowser` logic (`typeof process !== "undefined" && process.release?.name.search(/node|io.js/) !== -1`) in the deployed `iam-client-lib` gives the opposite result of what I would expect. In other words, if `process.release.name === "node"`, then above logic returns true.

This code for instance runs without error for me in Node.js using the `iam-client-lib` npm package:
```
import { IAM } from 'iam-client-lib'

(async () => {
    const iam = new IAM({
        privateKey: 'bafe62d65126513025b683a5a78b48c7ad5b4cea5661cfc9e5463b192ce3d408',
        rpcUrl: "https://volta-rpc.energyweb.org",
        chainId: 73799,
    })
    await iam.initializeConnection()
    await iam.createSelfSignedClaim({ "data": {test: "some data"}} )
})();
```

Expected behaviour would be that above code fails because `createSelfSignedClaim` has a check that it is running in browser:
```
  async createSelfSignedClaim({ data }: { data: Record<string, unknown> }) {
    if (!this._runningInBrowser) {
      throw new MethodNotAvailableInNodeEnvError("createSelfSignedClaim");
    }
```

**So what has me confused** is that were saying in Monday's standup that you ran into `MethodNotAvailableInNodeEnvErrors` when writing tests? And so I don't understand how you would have the errors, assuming the `isBrowser` logic is giving "opposite results".

**Comment by jrhender** [comment]
I think that the incorrect `isBrowser` logic isn't affecting Switchboard because the methods have `MethodNotAvailableInNodeEnvErrors` aren't being used in Switchboard:
`updateDidDocument` function -> not used in Switchboard
`revokeDidDocument` function -> not used in Switchboard

> > @JGiter I am confused however how the `isRunningBrowser` checks worked if the `isBrowser` logic was indeed incorrect
> > Does this make sense to you?
> 
> Probably webpack adds process object to the build
> image

Sorry, how did you get process to print out in the console? I don't see it when I try to access it: 
image

**Comment by JGiter** [comment]
> @JGiter So as I understand it, the `isBrowser` logic (`typeof process !== "undefined" && process.release?.name.search(/node|io.js/) !== -1`) in the deployed `iam-client-lib` gives the opposite result of what I would expect. In other words, if `process.release.name === "node"`, then above logic returns true.
> 
> This code for instance runs without error for me in Node.js using the `iam-client-lib` npm package:
> 
> ```
> import { IAM } from 'iam-client-lib'
> 
> (async () => {
>     const iam = new IAM({
>         privateKey: 'bafe62d65126513025b683a5a78b48c7ad5b4cea5661cfc9e5463b192ce3d408',
>         rpcUrl: "https://volta-rpc.energyweb.org",
>         chainId: 73799,
>     })
>     await iam.initializeConnection()
>     await iam.createSelfSignedClaim({ "data": {test: "some data"}} )
> })();
> ```
> 
> Expected behaviour would be that above code fails because `createSelfSignedClaim` has a check that it is running in browser:
> 
> ```
>   async createSelfSignedClaim({ data }: { data: Record<string, unknown> }) {
>     if (!this._runningInBrowser) {
>       throw new MethodNotAvailableInNodeEnvError("createSelfSignedClaim");
>     }
> ```
> 
> So what has me confused is that you were saying in Monday's standup that you ran into `MethodNotAvailableInNodeEnvErrors` when writing tests? And so I don't understand how you would have the errors, assuming the `isBrowser` logic is giving "opposite results".

**Comment by JGiter** [comment]
> > @JGiter So as I understand it, the `isBrowser` logic (`typeof process !== "undefined" && process.release?.name.search(/node|io.js/) !== -1`) in the deployed `iam-client-lib` gives the opposite result of what I would expect. In other words, if `process.release.name === "node"`, then above logic returns true.
> > This code for instance runs without error for me in Node.js using the `iam-client-lib` npm package:
> > ```
> > import { IAM } from 'iam-client-lib'
> > 
> > (async () => {
> >     const iam = new IAM({
> >         privateKey: 'bafe62d65126513025b683a5a78b48c7ad5b4cea5661cfc9e5463b192ce3d408',
> >         rpcUrl: "https://volta-rpc.energyweb.org",
> >         chainId: 73799,
> >     })
> >     await iam.initializeConnection()
> >     await iam.createSelfSignedClaim({ "data": {test: "some data"}} )
> > })();
> > ```
> > 
> > 
> > Expected behaviour would be that above code fails because `createSelfSignedClaim` has a check that it is running in browser:
> > ```
> >   async createSelfSignedClaim({ data }: { data: Record<string, unknown> }) {
> >     if (!this._runningInBrowser) {
> >       throw new MethodNotAvailableInNodeEnvError("createSelfSignedClaim");
> >     }
> > ```
> > 
> > 
> > So what has me confused is that you were saying in Monday's standup that you ran into `MethodNotAvailableInNodeEnvErrors` when writing tests? And so I don't understand how you would have the errors, assuming the `isBrowser` logic is giving "opposite results".

@jrhender You are right. Logic is incorrect. But in my case, the reason was that iam-client-lib used an old version of ew-did-registry, which led to failing of iam initialization and  createSubdomain throws MethodNotAvailableInNodeEnvError if some of the iam fields are not initialized

**Comment by JGiter** [comment]
> > > @JGiter So as I understand it, the `isBrowser` logic (`typeof process !== "undefined" && process.release?.name.search(/node|io.js/) !== -1`) in the deployed `iam-client-lib` gives the opposite result of what I would expect. In other words, if `process.release.name === "node"`, then above logic returns true.
> > > This code for instance runs without error for me in Node.js using the `iam-client-lib` npm package:
> > > ```
> > > import { IAM } from 'iam-client-lib'
> > > 
> > > (async () => {
> > >     const iam = new IAM({
> > >         privateKey: 'bafe62d65126513025b683a5a78b48c7ad5b4cea5661cfc9e5463b192ce3d408',
> > >         rpcUrl: "https://volta-rpc.energyweb.org",
> > >         chainId: 73799,
> > >     })
> > >     await iam.initializeConnection()
> > >     await iam.createSelfSignedClaim({ "data": {test: "some data"}} )
> > > })();
> > > ```
> > > 
> > > 
> > > Expected behaviour would be that above code fails because `createSelfSignedClaim` has a check that it is running in browser:
> > > ```
> > >   async createSelfSignedClaim({ data }: { data: Record<string, unknown> }) {
> > >     if (!this._runningInBrowser) {
> > >       throw new MethodNotAvailableInNodeEnvError("createSelfSignedClaim");
> > >     }
> > > ```
> > > 
> > > 
> > > So what has me confused is that you were saying in Monday's standup that you ran into `MethodNotAvailableInNodeEnvErrors` when writing tests? And so I don't understand how you would have the errors, assuming the `isBrowser` logic is giving "opposite results".
> 
> @jrhender You are right. Logic is incorrect. But in my case, the reason was that iam-client-lib used an old version of ew-did-registry, which led to failing of iam initialization and createSubdomain throws MethodNotAvailableInNodeEnvError if some of the iam fields are not initialized
Also I don't quite understand why the use of the library is limited by the browser? From the code I can see that MethodNotAvailableInNodeEnvError is thrown if _ensRegistry or _signer is not initialized. But they do not have to be initialized in the browser. In addition, this limitation makes testing difficult because I need somehow to simulate the browser

**Comment by jrhender** [comment]
@JGiter Took your advice and now using `Function` constructor to check the global scope, thanks.

**Comment by jrhender** [comment]
@JGiter nevermind, I went back to just checking the `process` variable because Function constructor approach fails if unsafe-eval is not allowed in Content Security Policy script-src directory

(below is a screenshot of trying it out in the Fastmail web app, which I just happened to have open)

image

**Review by JGiter — APPROVED** [review]

**Pull request merged**
