### PR TITLE
chore(logger): replace console log with logger

### PR DESCRIPTION
**Pull request by whitneypurdum**
### Description

Remove console.logs and replace with logger

### Contributor checklist

- [ ] Breaking changes - check for any existing interfaces changes that are not backward compatible, removed method etc.
- [ ] Documentation - document your code, add comments for method, remember to check if auto generated docs were updated.
- [ ] Tests - add new or updated existed test for changes you made.
- [ ] Migration guide - add migration guide for every breaking change.
- [ ] Configuration correctness - check that any configuration changes are correct ex. default URLs, chain ids, smart contract verification on [Volta explorer](https://volta-explorer.energyweb.org/) or [EWC explorer](https://explorer.energyweb.org/).

### CODE REVIEW

**Comment by whitneypurdum** [comment]
This was the only module that had console logging. Other instances of console logs were in the /scripts directory - I had originally changed to use logger there but then realized the task specifically stated it should be changed for modules.

**Comment by Harasz** [comment]
it's not only replacing the console log to logger, but also adding logger in other places. So we can easy debug the any problems in the future

**Review by jrhender — APPROVED** [review]
I think this is an improvement as is, so I think it worth it to merge as is

@whitneypurdum Just a reminder to either "Squash merge" the PR via the Github UI or `rebase -i` squash the commits before merging please

**Comment by jrhender** [comment]
@Harasz I think we can add other tasks/story to add additional logs

**Pull request merged**
