### PR TITLE
fix(exp): document expirationTimestamp

### PR DESCRIPTION
**Pull request by whitneypurdum**
### Description

Updates documentation for expirationTimestamp to be explicit that the timestamp is in milliseconds

### Contributor checklist

- [x] Breaking changes - check for any existing interfaces changes that are not backward compatible, removed method etc.
- [x] Documentation - document your code, add comments for method, remember to check if auto generated docs were updated.
- [x] Tests - add new or updated existed test for changes you made.
- [x] Migration guide - add migration guide for every breaking change.
- [x] Configuration correctness - check that any configuration changes are correct ex. default URLs, chain ids, smart contract verification on [Volta explorer](https://volta-explorer.energyweb.org/) or [EWC explorer](https://explorer.energyweb.org/).

### CODE REVIEW

**Review by nichonien — APPROVED** [review]

**Review by jrhender — CHANGES_REQUESTED** [review]
We should specific that it is a Unix timestamp (which I think is the case), the start date from which the milliseconds are added is important

**Comment by jrhender** [comment]
Actually, I see that a Unix timestamp is in seconds not miliseconds, so we can't say that is directly a Unix timestamp. Perhaps we should say that it is a "Unix timestamp expressed in milliseconds"?

**Comment by jrhender** [comment]
@whitneypurdum In this PR, @JGiter is using seconds as the unit for `RegisterOnchainOptions` which I think might be correct https://github.com/energywebfoundation/iam-client-lib/pull/636/files 
What are your thoughts?

**Comment by whitneypurdum** [comment]
@jrhender so just in registerOnChainClaim
Options is it seconds?

**Comment by whitneypurdum** [comment]
> @whitneypurdum In this PR, @JGiter is using seconds as the unit for `RegisterOnchainOptions` which I think might be correct https://github.com/energywebfoundation/iam-client-lib/pull/636/files What are your thoughts?

updated so  RegisterOnChainOptions is in seconds.

**Comment by jrhender** [comment]
@whitneypurdum I'm sorry, I'm looking at it again in and I think maybe it should be milliseconds in `RegisterOnchainOptions` and it is wrong in https://github.com/energywebfoundation/iam-client-lib/pull/636/files 
Maybe we merge with milliseconds in this PR and then we can debate seconds vs milliseconds in the other PR 😄

**Comment by whitneypurdum** [comment]
> @whitneypurdum I'm sorry, I'm looking at it again in and I think maybe it should be milliseconds in `RegisterOnchainOptions` and it is wrong in https://github.com/energywebfoundation/iam-client-lib/pull/636/files Maybe we merge with milliseconds in this PR and then we can debate seconds vs milliseconds in the other PR 😄

OKay @jrhender , I changed it back to milliseconds. We can't merge anyways till we figure out why the tests are failing. This PR doesn't have the updated packages and it is now failing. Maybe something wrong with cache server?

**Comment by whitneypurdum** [comment]
@jrhender Please can you review this one more time?

**Review by jrhender — APPROVED** [review]
looks good. Could you fix the merge conflicts when you have a moment please @whitneypurdum ?

**Pull request merged**
