### PR TITLE
update ew-credentials 2.0.1-alpha.275.0

### PR DESCRIPTION
**Pull request by JGiter**
### Contributor checklist

- [x] Breaking changes - check for any existing interfaces changes that are not backward compatible, removed method etc.
- [x] Documentation - document your code, add comments for method, remember to check if auto generated docs were updated.
- [x] Tests - add new or updated existed test for changes you made.
- [x] Migration guide - add migration guide for every breaking change.
- [x] Configuration correctness - check that any configuration changes are correct ex. default URLs, chain ids, smart contract verification on [Volta explorer](https://volta-explorer.energyweb.org/) or [EWC explorer](https://explorer.energyweb.org/).

### CODE REVIEW

**Comment by nichonien** [comment]
@JGiter We can use the latest version of `ew-did-registry` which is `[0.7.1-alpha.808.0](https://www.npmjs.com/package/@ew-did-registry/did/v/0.7.1-alpha.808.0)` . This has my changes, thanks!

**Comment by JGiter** [comment]
> @JGiter We can use the latest version of `ew-did-registry` which is `0.7.1-alpha.808.0` . This has my changes, thanks!

Is this require another round of updating of ew-credentials?

**Comment by nichonien** [comment]
> Is this require another round of updating of ew-credentials?

No, only the `ew-did-registry` has the changes.

**Comment by nichonien** [comment]
@JGiter My bad, there is a signature change for method and this is resulting is workflow fail. Maybe you can go back to the older version and I would update to latest making these changes in `iam-cleint-lib`.

**Comment by JGiter** [comment]
> @JGiter My bad, there is a signature change for method and this is resulting is workflow fail. Maybe you can go back to the older version and I would update to latest making these changes in `iam-cleint-lib`.

Ok, I'll revert

**Review by nichonien — APPROVED** [review]

**Pull request merged**
