### PR TITLE
bug/ICL-223 v4.1 breaking changes were not added to changelog

### PR DESCRIPTION
**Pull request by JGiter**
https://energyweb.atlassian.net/browse/ICL-223

Changes in question https://github.com/energywebfoundation/iam-client-lib/pull/431

### CODE REVIEW

**Comment by JGiter** [comment]
@jrhender It appears that not only Changelog was not updated, but instead of major the minor version was bumped. I could commit this PR as breaking change to fix that. What do you think?

**Comment by Harasz** [comment]
@JGiter I think we should revert #431 and commit changes again but we braking change mark.

**Comment by jrhender** [comment]
> @JGiter I think we should revert #431 and commit changes again but we braking change mark.

I think that probably this is the best way, generally speaking. But as we've already merged a "breaking change" PR (https://github.com/energywebfoundation/iam-client-lib/pull/450), I don't think it matters much. Which ever you guys prefer.

**Review by jrhender — APPROVED** [review]

**Pull request merged**
